### ISSUE TITLE
Adding pages in SurveyJS builder - some browser compatibility issues?

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/surveyjs#1030]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a (possible) bug

### What is the current behavior?

In both Internet Explorer and Chrome, adding & changing pages in your survey through the SurveyJS builder doesn't seem to work well. When adding pages, this is only partly processed (i.e. in the dropdown but not in the horizontal overview next to it for example, nor do you automatically switch to that new page).
Changing between pages sometimes doesn't work or takes really long (both when doing it through the page-dropdown and through the horizontal overview of pages next to it).

Firefox seems to work OK, albeit a bit slow especially when changing pages (even when those pages contain no questions)

### What is the expected behavior?

I would expect that adding pages and changing pages functions in all browsers like it does in Firefox, if possible a bit faster.

### How would you reproduce the current behavior (if this is a bug)?
Go to https://www.surveyjs.io/Survey/Builder/ on different browsers and try to add pages to your survey/change pages etc. Either it will be clear quickly what I mean or somehow the issue can't be reproduced.

Example of how it looks in Internet Explorer: 
![afbeelding](https://user-images.githubusercontent.com/31244247/38081799-72eeb9de-3334-11e8-943a-c2485d3c8c67.png)

In Chrome the pages seem to add a bit better (though sometimes really slow) but when you click on a page in the horizontal overview, it doesn't load.

In Firefox everything seems to work like it should, although changing between pages (even when the pages contain no questions) takes quite long.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://www.surveyjs.io/Survey/Builder/ 
(SurveyJS 1.0.15)

### Specify your
Browsers:
Chrome = 55.0.2883.87 m
Internet Explorer = 11.0.9600.18816
Firefox = 50.1.0

**Comment by tsv2013** [comment]
This bug is related to the https://github.com/surveyjs/editor repo
Fixed via the https://github.com/surveyjs/editor/commit/40e6701186dc7e9bdf7a7eac9414dce362072fc8 commit
Fix will be available in the nearest update

**Comment by Lynn42** [comment]
Chrome works fine right now! However, Internet Explorer still does not work for adding pages/changing between pages.

**Comment by tsv2013** [comment]
Reopened. I'll fix it.
