### ISSUE TITLE
Bootstrap4 - radio group && Checkbox - layout

### ISSUE THREAD

**Issue by ThierryNapspirit** [surveyjs/surveyjs#1127]
## Bug layout bootstrap4
Layout bug with Bootstrap v4 (tested with Linux):
- it works with Firefox
- it does not work with Chrome, Vivaldi, Opera
I didn't test with Safari or Edge.

bootstrap4 "colcount" does not work ("radio group" and  "check box").

- [Radio Group bootstrap 4.1.1  - colcount=4 - bug](https://plnkr.co/edit/IQOKLnotXmQ0tHg9mJFa?p=preview)
- [Radio group bootstrap 3.7 - colcount=4](https://plnkr.co/edit/ElFCKVf3PDNK5decZUXj?p=preview)

Similar problem with colcount=0 , colcount=1 ....

### Fix ?

The (bad?) way I fixed it (tested on Firefox, Chrome, Opera, Vivaldi).

    .sv_bootstrap_css fieldset  {    
        display: block !important;
    }

    .sv_bootstrap_css .sv_q_checkbox_inline {
        display: inline-flex;
    }

    .sv_bootstrap_css .sv_q_radiogroup_inline {
        display: inline-flex;
    }

- [Radio Group bootstrap 4.1.1  - colcount=4 - fixed](https://plnkr.co/edit/kdVaSH4EnUHy8rLjoj5u?p=preview)

**Comment by tsv2013** [comment]
Thank you for the report. I've fixed it. Fix will be available in the nearest update.

**Comment by ThierryNapspirit** [comment]
Thanks for this.

Sorry to bother you again but I think part of the bug is not fixed with your commit.

You added CSS code ".sv_bootstrap_css .sv_qstn fieldset": "display: block;"  but not the "inline-flex" code.
According to my tests, your code will only fix the problem with colcount=1,2,3 or 4... but it won't work with colcount=0.

Here is an example (does not work with Chrome): [Radio group bootstrap 4.1.1 colcount=0](https://plnkr.co/edit/x4sdN7Uj8u2Wrw1iAYxS?p=preview)

Without "inline-flex" colcount=0 will be similar to colcount=1.

I think you also need to add the "inline-flex" CSS lines.

**Comment by tsv2013** [comment]
Thank you for the thorough testing, @ThierryNapspirit. I highly appreciate it.
Ufortunately zero colCount case dudn't work for BS3 either. I've added the fix for both boorstraps.
