### ISSUE TITLE
'other' resets value

### ISSUE THREAD

**Issue by StephanMeijer** [surveyjs/surveyjs#1538]
### Are you requesting a feature, reporting a bug or asking a question?

Bug.

### What is the current behavior?

It resets a whole option when I select 'other' and fill in some value'

### What is the expected behavior?

It should work™️ 

### How would you reproduce the current behavior (if this is a bug)?

Great Question, no idea.

#### Provide the test code and the tested page URL (if applicable)

![surveyjs-other](https://user-images.githubusercontent.com/3169264/52539983-cf65d080-2d84-11e9-8532-8fb9e7209b12.gif)

### Specify your

* browser: Chrome 
* browser version: Version 71.0.3578.98 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: `"survey-react": "^1.0.1",`

**Comment by tsv2013** [comment]
Unfortunately I've not managed to reproduce this issue in our online demo - https://surveyjs.io/Examples/Library/?id=questiontype-dropdown&platform=Reactjs&theme=default

Could you provide us with a small sample or plunker illustrating the issue?

**Comment by StephanMeijer** [comment]
Possibly related: https://github.com/surveyjs/surveyjs/issues/1535

**Comment by dmitrykurmanov** [comment]
We've fixed the bug. Fix will be available in the next minor update.

**Comment by StephanMeijer** [comment]
@tmvnk 🎉

**Comment by StephanMeijer** [comment]
Are you sure you fixed the issue @dmitrykurmanov ? Still appears to occur on `1.0.69`

**Comment by StephanMeijer** [comment]
Disabling timer does not solve this specific issue.

**Comment by andrewtelnov** [comment]
@StephanMeijer Could you please try v1.071. We should fix it in the latest version.

Thank you,
Andrew

**Comment by StephanMeijer** [comment]
Fixed @andrewtelnov 

Thank you
