### ISSUE TITLE
Only a ReactOwner can have refs?

### ISSUE THREAD

**Issue by ericdmessick** [surveyjs/surveyjs#225]
I'm trying to run the survey locally with React, but I keep getting this error.  

"Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded"

The first page of the survey renders, but throws this error.   And if you click anything, the error throws again and nothing works.  

I've tried researching the bug. I have no "ref"s in my code so that leads me to believe its a duplicate copy of react.  I've tried uninstalling and reinstalling node, survey, and so on.  Seeing as all the libraries we downloaded didn't throw this error and it only started when I started using survey.js.

The app code is located here.  

https://github.com/ericdmessick/SurveyForDummies/

Please, help.

**Comment by andrewtelnov** [comment]
@ericdmessick Probably this [stackoverflow topic](http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean) will solve the issue. 

> I encountered this error when a component module I was using had it's own react dependency installed. So I was using multiple versions of React.

Please let us know does it help.

Thank you,
Andrew

**Comment by ericdmessick** [comment]
No, sir.  I had found that page before and gone through the suggested fixes to no avail.

**Comment by andrewtelnov** [comment]
Ok, I will try out your project then.

**Comment by andrewtelnov** [comment]
@ericdmessick There are two versions :-) react 14.x and react 15.x. You may go to "node_modules" and in survey-react directory you will find another "node_modules" that contains react 15.x.

I have corrected your package.json, reinstall the packages, and the app runs fine. 
```
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^15.4.2",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "babel-preset-stage-1": "^6.1.18",
    "lodash": "^3.10.1",
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-redux": "^5.0.2",
    "react-router": "^2.0.1",
    "redux": "^3.0.4",
    "survey-react": "^0.11.0"
  }

```

Thank you,
Andrew

**Comment by ericdmessick** [comment]
Okay, I got it to work too.  Thank you so much for taking the time.

Apparently, I still have a lot to learn about node.  If I'm understanding the inner workings of this correctly, the reason you have to uninstall the packages, change the json, and then reinstall the packages is because node actually has to rebuild the system with the correct references.  That is why you can't just change the JSON to fix it?

**Comment by andrewtelnov** [comment]
I was using the command line. So changing a text/json file did nothing :-)
