### ISSUE TITLE
Custom widgets for http://antenna.io/demo/jquery-bar-rating/examples/

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/surveyjs#281]
vue: https://plnkr.co/edit/tMojBg8fWAmnALaziiBi?p=preview

**Comment by dmitrykurmanov** [comment]
[icheck](http://icheck.fronteed.com/)

**Comment by dmitrykurmanov** [comment]
[select2](https://select2.github.io/)

**Comment by mellogarrett** [comment]
Getting `Cannot read property 'Instance' of undefined` with:

```
          var widget = {
            name: "star-rating",
            htmlTemplate: "<div id='star-rating'>",
            isFit : function(question) { return question['renderAs'] == 'star-rating'; },
            afterRender: function(question, el) {
              var widget = $(el).find('#star-rating').barrating({ theme: 'fontawesome-stars' });
            }
          }
          Survey.CustomWidgetCollection.Instance.addCustomWidget(widget);
```

**Comment by mellogarrett** [comment]
^ Using jQuery

**Comment by mellogarrett** [comment]
<img width="249" alt="screen shot 2017-03-03 at 3 00 11 pm" src="https://cloud.githubusercontent.com/assets/9908831/23566963/275915aa-0022-11e7-8b96-4699265b3003.png">

Hmmm... no `CustomWidgetCollection`?

**Comment by mellogarrett** [comment]
Weird, seems like it's only the minified jQuery version that I have this issue with.

**Comment by dmitrykurmanov** [comment]
@mellogarrett which version of survey-jquery do you use?

**Comment by dmitrykurmanov** [comment]
@mellogarrett Hello! _barrating_ wants dom select with options and doesn't generate it by itself. We thought it would be good to have `isDefaultRender` flag for custom widget. It allows us to use surveyjs default DOM(select) for controls like  _barrating_ . So we implemented it. Please check an example here:

https://plnkr.co/edit/Vps5IAZ41Tc5fuDH8YPk?p=preview

We'll include this feature in next realese. Or you can build surveyjs by yourself. Thanks!

**Comment by mellogarrett** [comment]
Unable to build the library from source. Not sure the issue, but I don't end up with a `dist` directory

**Comment by tsv2013** [comment]
@mellogarrett What errors did you receive?

**Comment by mellogarrett** [comment]
That's the thing.. I don't see any obvious errors

**Comment by tsv2013** [comment]
@mellogarrett Build results should be in the packages folder.

**Comment by mellogarrett** [comment]
Ahh! There it is. I was looking for `dist` as the README still specifies.

**Comment by tsv2013** [comment]
I've updated readme. Thank you, @mellogarrett !

**Comment by mellogarrett** [comment]
FYI still getting the weird issue in the minified version where `Survey.CustomWidgetCollection` is undefined. Dev version doesn't have that issue

**Comment by tsv2013** [comment]
Thank you, we'll check it.

**Comment by mellogarrett** [comment]
I'm in dire need of some better Custom Widget docs. I can't get it to work with the code:

```
          var widget = {
            name: "antennaio-jquery-bar-rating",
            isFit : function(question) { return question["renderAs"] === 'starRating'; },
            isDefaultRender: true,
            afterRender: function(question, el) {
              $(el).find('select').find('option')[0].remove(); //removed default option
              $(el).find('select').barrating('show', {
                  theme: 'bootstrap-stars',
                  initialRating: question.value,
                  showSelectedRating: false,
                  allowEmpty: true,
                  emptyValue: '-- no rating selected --',
                  onSelect: function(value, text) {
                      question.value = value;
                  }
              });

              question.valueChangedCallback = function() {
                  $(el).find('select').barrating('set', question.value);
              }
            }
          }

          Survey.CustomWidgetCollection.Instance.addCustomWidget(widget);
```

But it works if I manually run: 

```
$('#sq_100i').barrating({theme: 'bootstrap-stars'});
```

**Comment by mellogarrett** [comment]
Specifically, how does `htmlTemplate` and `isDefaultRender` work?

Currently with `isDefaultRender: true`, it replaces my:

```
<div>
  <select>
    <option>
    ...
  </select>
</div>
```

with just `<div></div>`

**Comment by dmitrykurmanov** [comment]
@mellogarrett, Could you create (or fork our) plunk and give us the link on it? 

PS: You can use your own html with `htmlTemplate` or use `isDefaultRender: true` for our default markup. And we think about docs, but we have only examples at the moment.

**Comment by mellogarrett** [comment]
@dmitrykurmanov Okay I have the star-rating working. Couple of odd things happening though. 

1) When I go back to a star-rating question using `previous`, it does not re-render the widget.
2) The `onSelect` within the `afterRender` fires 3 times??
Here's the code for that:

```
afterRender: function(question, el) {
  $(el).find('select').find('option')[0].remove(); //removed default option
  $(el).find('select').barrating('show', {
  theme: 'bootstrap-stars',
  initialRating: question.value,
  showSelectedRating: false,
  allowEmpty: true,
  emptyValue: '-- no rating selected --',
  onSelect: function(value, text) {
    console.log("value: " + value);
    question.value = value;
  }
});
```

**Comment by tsv2013** [comment]
@mellogarrett Please check updated [plunker](https://plnkr.co/edit/rvY7Wa2peHlDFq9lDCFt?p=preview)
It looks like barrating cann't update previous instance. And we need to destroy it on re-render:

```
var widget = {
    name: "antennaio-jquery-bar-rating",
    isFit : function(question) { return question["renderAs"] === 'barrating'; },
    isDefaultRender: true,
    afterRender: function(question, el) {
        $(el).find('select').barrating('destroy');
        $(el).find('select').barrating('show', {
            theme: 'fontawesome-stars',
            initialRating: question.value,
            showSelectedRating: false,
            onSelect: function(value, text) {
                question.value = value;
            }
        });

        question.valueChangedCallback = function() {
            $(el).find('select').barrating('set', question.value);
        }
    }
}
```
