### ISSUE TITLE
Radiogroup comments disappear when submitting survey

### ISSUE THREAD

**Issue by fz6** [surveyjs/surveyjs#390]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

`hasComment` property on `radiogroup` questions does not work correctly. The comment is lost (has disappeared when `onComplete` fires). Also, the pagination breaks when this property is set (second page / second question disappears in provided example)

### What is the expected behavior?

When the `onComplete` event fires, I should be able to see the comment in `s.data` and/or `survey.data`

### How would you reproduce the current behavior (if this is a bug)?

See attached Plunker.

The comment is definitely stored on `survey.data` until you hit complete (see console window while using example)

#### Provide the test code and the tested page URL (if applicable)

http://plnkr.co/edit/0svJdA4wk5d19uvcJZvk?p=preview

### Specify your

* browser: `Chrome`
* browser version: `58.0.3029.96`
* surveyjs platform `jquery`
* surveyjs version: `0.12.14`

**Comment by fz6** [comment]
This can also be reproduced using your Survey Editor - http://surveyjs.org/builder/#d91bfe4d-6a94-42be-b51a-943c6f969644

**Comment by tsv2013** [comment]
I've fixed this. The fix will be available in the nearest update. If you have any deadline, we can release maintenance update ASAP.

**Comment by fz6** [comment]
Thanks, confirmed that has resolved the comment issue.

However, pagination is still broken for this example (page 2 is missing). Tested locally with same plunk downloaded and pointed to a build of 699996c done locally (plunkr didn't like such a large JS file so I haven't updated example, sorry).

No rush on an update, still developing and happy to build from source for the moment. Thanks for resolving so quickly!

**Comment by tsv2013** [comment]
@fz6 Yes, I've missed pagination issue. Sorry.

**Comment by tsv2013** [comment]
The
`     type: "radiogroup",
`
is missed for the question on the second page. This is why the second page is invisible.

**Comment by tsv2013** [comment]
@fz6  I think we can close this issue now :-)

**Comment by fz6** [comment]
Oh man @tsv2013 , that's embarrassing, my bad!

Yes, I think we can.

I do have one more question, hopefully a quick one (though I can open a separate issue if preferred).

I can't quite figure out where the jQuery 'templates' live (or where the rendering occurs). For all the others it's easy. As an example, for Angular/KO/React/Vue I can see exactly where `colCount` is used to determine the radiobutton width, (i.e. [for Vue](https://github.com/surveyjs/surveyjs/blob/master/src/vue/radiogroup.vue#L26)), but I can't for the life of me figure out how it's done for the jQuery version.

**Comment by tsv2013** [comment]
@fz6  jQuery and Angular solutions are working over `survey-react` implementation. You can find markup in the corresponding render functions of the react components in the `/src/react` folder.

**Comment by fz6** [comment]
Thanks a lot @tsv2013 , I get it now :-) Closing issue now, thanks again for resolving this so quickly.
