### ISSUE TITLE
Lots of warnings with current React

### ISSUE THREAD

**Issue by mikecousins** [surveyjs/surveyjs#703]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Lots of errors/warnings when used with current React.

When installing:
`warning "survey-react@0.12.30" has incorrect peer dependency "react@^15.0.1"`
`warning "survey-react@0.12.30" has incorrect peer dependency "react-dom@^15.0.1".`

When running:
`Warning: Survey.componentWillReceiveProps(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.`
`Warning: SurveyQuestion.componentWillReceiveProps(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.`
`Warning: SurveyQuestionErrors.componentWillReceiveProps(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.`

### What is the expected behavior?
No errors/warnings.

### How would you reproduce the current behavior (if this is a bug)?
Create a project with React 16 and try to use survey-react with it.

### Specify your

* browser: Chrome
* browser version: 61
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 0.12.30

**Comment by andrewtelnov** [comment]
@mikecousins We have fixed this issue: https://github.com/surveyjs/surveyjs/issues/702
The version that has been released today should be fine.

Thank you,
Andrew

**Comment by mikecousins** [comment]
We still get some warnings when we install packages:

```
warning "survey-react@0.12.32" has incorrect peer dependency "react@^15.0.1".
warning "survey-react@0.12.32" has incorrect peer dependency "react-dom@^15.0.1".
```

Maybe the dependency in package.json needs to be updated?

**Comment by andrewtelnov** [comment]
@tsv2013 @dmitrykurmanov Could you please take a look at this issue?

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
I will check it

**Comment by dmitrykurmanov** [comment]
please see https://github.com/surveyjs/surveyjs/issues/718
