### ISSUE TITLE
Online Editor Crashing on setting "boolean" to column.cellType in Matrix Dynamic question.

### ISSUE THREAD

**Issue by murrah** [surveyjs/surveyjs#707]
### Are you requesting a feature, reporting a bug or ask a question?
Bug in 0.12.31

### What is the current behavior?
Add a matrix question, edit it, change a column Cell type to Boolean, click OK button, throws this in console:
question_matrixdynamic.ts:293 Uncaught TypeError: Cannot read property 'indexOf' of null
    at QuestionMatrixDynamicModel.getRowValueCore (question_matrixdynamic.ts:293)
    at QuestionMatrixDynamic.QuestionMatrixDropdownModelBase.onRowChanged (question_matrixdropdownbase.ts:673)
    at MatrixDynamicRowModel.MatrixDropdownRowModelBase.setValue (question_matrixdropdownbase.ts:207)
    at QuestionBoolean.Question.setValueCore (question.ts:383)
    at QuestionBoolean.Question.setNewValueInData (question.ts:375)
    at QuestionBoolean.Question.setNewValue (question.ts:369)
    at QuestionBoolean.set [as value] (question.ts:251)
    at QuestionBooleanModel.setDefaultValue (question_boolean.ts:81)
    at QuestionBoolean.Question.updateValueWithDefaults (question.ts:271)
    at QuestionBoolean.Question.onSetData (question.ts:238)

### What is the expected behavior?
Be able to save changes

### How would you reproduce the current behavior (if this is a bug)?
See above
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 0.12.31

**Comment by andrewtelnov** [comment]
@murrah Yes, indeed. I do check it with MatrixDropdown in Editor. There was an issue with Matrix Dynamic.
It is fixed now.

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov Sorry, but it appears to still not work with Matrix Dynamic. The error is not thrown but I can't save the dialog.

1. Started new survey with 0.12.31
2. Dragged Matrix Dynamic onto canvas
3. Clicked Edit then Columns 
4. On column 1 Cell type dropdown selected Boolean. The "edit" icon appears under the Required? column.
5. Click the `Ok` button and the dialog does nothing. No save. `Cancel` works.

Choosing other options from the dropdown (eg radio group) it saves ok, but once I try to select Boolean I cant save anymore.

With Matrix Multiple Choice it all works as expected. 

Thanks,
Murray

**Comment by andrewtelnov** [comment]
@murrah Yes, the fix will be available in the next release. I may update the "dev" version if you need it.

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov All good. Next version is fine. Just letting you know. Thanks.
