### ISSUE TITLE
Angular2 Page visibleIf Issue

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs#826]
### Are you requesting a feature, reporting a bug or ask a question?

Bug/Question

### What is the current behavior?

I have a survey such as:

```
{
 pages: [
  {
   elements: [
    {
     type: "radiogroup",
     choices: [
      "1",
      "2"
     ],
     name: "q1"
    }
   ],
   name: "page1"
  },
  {
   elements: [
    {
     type: "checkbox",
     choices: [
      "item1",
      "item2"
     ],
     name: "question1"
    }
   ],
   name: "page2",
   visible: false,
   visibleIf: "{q1} > 1"
  }
 ]
}
```

where the second page visibility is conditional on a question from the first page. This works fine on the editor and on plunker. However, I can't seem to make it work with Angular. 

I've also tried putting logging during onValueChanged and can see that those listeners are functioning properly.

### How would you reproduce the current behavior (if this is a bug)?
I'm using:
```
"@angular/common": "5.0.0",
"survey-angular": "^0.12.36",
```

The bug seems to be specific to my setup and I'm unable to reproduce on the Editor or Plunker. Do you have any suggestions on what would prevent this particular feature to not function?

### Specify your

* browser: Chrome
* browser version: 62.0.3202.94
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 0.12.36 from https://www.npmjs.com/package/survey-angular

**Comment by andrewtelnov** [comment]
@wollerman Could you please try it with the latest version, v0.98.3? I remember, I have fixed a bug related to this some times ago.

Thank you,
Andrew

**Comment by wollerman** [comment]
@andrewtelnov I didn't realize I was so far behind and updated! package.json is now at `"survey-angular": "^0.98.3",`

Unfortunately that didn't fix my issue. I've tested the above form json with no success. Opening devtools I can see that the console is logging for `surveyModel.onValueChanged.add(this.valueChanged);`. But the inspector doesn't show any changes in the footer. At first I was suspecting that maybe my custom CSS was covering up the button change or something. Here's the full tag rendered no matter which option is selected from the above survey:

```
<div class="panel-footer card-footer">
<input class="btn sv_complete_btn" type="button" value="Submit" style="margin-right: 5px;">
</div>
```

Is there any sort of property that I could have inadvertently set which would influence visibleIf triggers? These are all the properties I'm setting before survey render:
```
    surveyModel.showCompletedPage = false;
    surveyModel.showTitle = false;
    surveyModel.showProgressBar = 'top';
    surveyModel.sendResultOnPageNext = true;
    surveyModel.focusFirstQuestionAutomatic = false;
    surveyModel.clearInvisibleValues = 'onComplete';
    surveyModel.pagePrevText = 'Go Back';
    surveyModel.pageNextText = 'Go Forward';
    surveyModel.completeText = "Submit";

    surveyModel.onValueChanged.add(this.valueChanged);
    surveyModel.onPartialSend.add(this.saveSurveyData);
    surveyModel.onComplete.add(this.saveSurveyData);
```

`saveSurveyData()` is some method calling a provider. And `valueChanged()` is simply:

```
  valueChanged = () => {
    console.log('value changed');
  };
```

**Comment by andrewtelnov** [comment]
@wollerman I do not see any problem with your code that you have provide to us.
Unfortunately, it is really hard to say what is going on.
When any value is changed in the survey, the survey asks all elements to re-run their expresions (visibleIf and enableIf) with new values.
It has nothing to do with onValueChanged events and others.
It may stop work, if your code on events produced an error, then a browser stops running JavaScript and as result the operation on value change is aborted.

Do you have any error in console? I do not know where do you call the code you have provided. Maybe it should be:
var self = this;
```
 surveyModel.onValueChanged.add(self.valueChanged);
surveyModel.onPartialSend.add(self.saveSurveyData);
surveyModel.onComplete.add(self.saveSurveyData);
```

Thank you,
Andrew
