### ISSUE TITLE
Error when trying to use survey-vue in a vue project with typescript

### ISSUE THREAD

**Issue by abritopach** [surveyjs/surveyjs#919]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

I try to use survey-vue in a vue project with **typescript**.

I have installed survey-vue: npm install survey-vue

When I try to import it follow vue quickstart repo 

import * as SurveyVue from  'survey-vue'
let Survey = SurveyVue.Survey

I get the following error:

Property 'Survey' does not exist on type 'typeof ".../vue/vue-surveyjs/node_modules/survey-vue/survey.vue"'.

### What is the expected behavior?

Import the survey vue version.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): vue "survey-vue": "^1.0.7",
* surveyjs version:

**Comment by tsv2013** [comment]
Wrong .d.ts file is generated due to the "export default class" declaration in the .vue files.
We'll fix it.

**Comment by abritopach** [comment]
Thanks @tsv2013

**Comment by tsv2013** [comment]
@abritopach I've changed export options. You can check it after nearest minor update.

**Comment by abritopach** [comment]
Thanks @tsv2013 

I was able to import replacing **export default class** with **export class** in survey.vue.d.ts but now I get the following error:

---------

vue.esm.js?efeb:578 [Vue warn]: Error in render: "TypeError: Cannot read property 'root' of undefined"

found in

---> <Survey> at src/vue/survey.vue
       <SurveyDetails> at src/components/SurveyDetails.vue
         <VApp>
           <App> at src/App.vue
             <Root>
warn @ vue.esm.js?efeb:578
logError @ vue.esm.js?efeb:1713
globalHandleError @ vue.esm.js?efeb:1708
handleError @ vue.esm.js?efeb:1697
Vue._render @ vue.esm.js?efeb:4476
updateComponent @ vue.esm.js?efeb:2765
get @ vue.esm.js?efeb:3115
Watcher @ vue.esm.js?efeb:3104
mountComponent @ vue.esm.js?efeb:2772
Vue$3.$mount @ vue.esm.js?efeb:8429
Vue$3.$mount @ vue.esm.js?efeb:10790
init @ vue.esm.js?efeb:4065
createComponent @ vue.esm.js?efeb:5512
createElm @ vue.esm.js?efeb:5460
updateChildren @ vue.esm.js?efeb:5749
patchVnode @ vue.esm.js?efeb:5840
patch @ vue.esm.js?efeb:6000
Vue._update @ vue.esm.js?efeb:2647
updateComponent @ vue.esm.js?efeb:2765
get @ vue.esm.js?efeb:3115
run @ vue.esm.js?efeb:3192
flushSchedulerQueue @ vue.esm.js?efeb:2954
(anonymous) @ vue.esm.js?efeb:1813
flushCallbacks @ vue.esm.js?efeb:1734
Promise.then (async)
microTimerFunc @ vue.esm.js?efeb:1782
nextTick @ vue.esm.js?efeb:1826
(anonymous) @ vue.esm.js?efeb:8434
(anonymous) @ vue.esm.js?efeb:10809
(anonymous) @ build.js:759
__webpack_require__ @ build.js:679
fn @ build.js:89
(anonymous) @ 307:2
(anonymous) @ build.js:2618
__webpack_require__ @ build.js:679
fn @ build.js:89
(anonymous) @ build.js:2473
__webpack_require__ @ build.js:679
(anonymous) @ build.js:725
(anonymous) @ build.js:728
vue.esm.js?efeb:1717 TypeError: Cannot read property 'root' of undefined
    at Proxy.render (survey.vue.js?4207:24268)
    at VueComponent.Vue._render (vue.esm.js?efeb:4474)
    at VueComponent.updateComponent (vue.esm.js?efeb:2765)
    at Watcher.get (vue.esm.js?efeb:3115)
    at new Watcher (vue.esm.js?efeb:3104)
    at mountComponent (vue.esm.js?efeb:2772)
    at VueComponent.Vue$3.$mount (vue.esm.js?efeb:8429)
    at VueComponent.Vue$3.$mount (vue.esm.js?efeb:10790)
    at init (vue.esm.js?efeb:4065)
    at createComponent (vue.esm.js?efeb:5512)

-----

Relevant code

```
import * as SurveyVue from  'survey-vue'
let Survey = SurveyVue.Survey

...

<template>
  <div>
    <p>Survey Details</p>
    <survey :survey="survey"></survey>
  </div>
</template>

...

showSurvey() {
    console.log("showSurvey");

    let surveyJSON = { title: 'Product Feedback Survey Example', showProgressBar: 'top', pages: [
        {
          questions: [{
              type: 'matrix',
              name: 'Quality',
              title: 'Please indicate if you agree or disagree with the following statements',
              columns: [{
                  value: 1,
                  text: 'Strongly Disagree'
                },
                {
                  value: 2,
                  text: 'Disagree'
                },
                {
                  value: 3,
                  text: 'Neutral'
                },
                {
                  value: 4,
                  text: 'Agree'
                },
                {
                  value: 5,
                  text: 'Strongly Agree'
                }
              ],
              rows: [{
                  value: 'affordable',
                  text: 'Product is affordable'
                },
                {
                  value: 'does what it claims',
                  text: 'Product does what it claims'
                },
                {
                  value: 'better then others',
                  text: 'Product is better than other products on the market'
                },
                {
                  value: 'easy to use',
                  text: 'Product is easy to use'
                }
              ]
            },
            {
              type: 'rating',
              name: 'satisfaction',
              title: 'How satisfied are you with the Product?',
              mininumRateDescription: 'Not Satisfied',
              maximumRateDescription: 'Completely satisfied'
            },
            {
              type: 'rating',
              name: 'recommend friends',
              visibleIf: '{satisfaction} > 3',
              title: 'How likely are you to recommend the Product to a friend or co-worker?',
              mininumRateDescription: 'Will not recommend',
              maximumRateDescription: 'I will recommend'
            },
            {
              type: 'comment',
              name: 'suggestions',
              title: 'What would make you more satisfied with the Product?',
            }
          ]
        }, {
          questions: [{
              type: 'radiogroup',
              name: 'price to competitors',
              title: 'Compared to our competitors, do you feel the Product is',
              choices: ['Less expensive', 'Priced about the same', 'More expensive', 'Not sure']
            },
            {
              type: 'radiogroup',
              name: 'price',
              title: 'Do you feel our current price is merited by our product?',
              choices: ['correct|Yes, the price is about right',
                'low|No, the price is too low for your product',
                'high|No, the price is too high for your product'
              ]
            },
            {
              type: 'multipletext',
              name: 'pricelimit',
              title: 'What is the... ',
              items: [{
                  name: 'mostamount',
                  title: 'Most amount you would every pay for a product like ours'
                },
                {
                  name: 'leastamount',
                  title: 'The least amount you would feel comfortable paying'
                }
              ]
            }
          ]
        }, {
          questions: [{
            type: 'text',
            name: 'email',
            title: 'Thank you for taking our survey. Please enter your email address, then press the "Submit" button.'
          }]
        }]
    };
    this.survey = new SurveyVue.SurveyModel(surveyJSON);
    console.log(this.survey);
  }

```

Thanks!!

**Comment by tsv2013** [comment]
I was not able to reproduce the issue with `root` using your JSON.

We've released v1.0.8 with this fix yesterday. Could you check it?

**Comment by abritopach** [comment]
Hello again @tsv2013 

I tried the new version but still get the same error. 

Also, new .d.ts file generated is wrong. I've had to remove duplicate lines of export code like the following:

```
export declare class SurveyElement extends Vue {
    css: any;
    survey: SurveyModel;
    element: IElement;
    getWidgetComponentName(element: QuestionModel): string;
    readonly hasErrorsOnTop: boolean;
    readonly hasErrorsOnBottom: boolean;
    mounted(): void;
}
export default SurveyElement; --> REMOVED

export declare class MatrixCell extends Vue {
    question: Question;
    cell: MatrixDropdownCell;
    getWidgetComponentName(element: QuestionModel): string;
    mounted(): void;
}
export default MatrixCell; --> REMOVED
```

And get "Cannot find the name' QuestionModel" in several parts of the file.

I have compared **my project** and the **surveyjs_vue_quickstart** and when I show survey model in Chrome Developer Console i get

```
surveyjs_vue_quickstart
-----------------------
var model = new SurveyVue.Model(json)
console.log(model);

VueSurveyModel {propertyHash: {…}, localizableStrings: {…}, arraysInfo: {…}, onPropChangeFunctions: Array(0), isLoadingFromJsonValue: false, …}
PageCount:(...)
arraysInfo:(...)
clearInvisibleValues:(...)
clientId:(...)
commentPrefix:(...)
comments:(...)
completeText:(...)
completedBeforeHtml:(...)
completedHtml:(...)
completedState:(...)
completedStateText:(...)
completedStateTextValue:(...)
completedStateValue:(...)
cookieName:(...)
css:(...) --> CSS KEY
currentPage:(...)
...
```

```
my project
-----------------------
this.survey = new SurveyVue.SurveyModel(surveyJSON);
console.log(this.survey);

SurveyModel {propertyHash: {…}, localizableStrings: {…}, arraysInfo: {…}, onPropChangeFunctions: Array(2), isLoadingFromJsonValue: false, …}
PageCount:(...)
arraysInfo:{pages: {…}, triggers: {…}}
clearInvisibleValues:(...)
clientId:(...)
commentPrefix:(...)
comments:(...)
completeText:(...)
completedBeforeHtml:(...)
completedHtml:(...)
completedState:(...)
completedStateText:(...)
completedStateTextValue:""
completedStateValue:""
cookieName:(...)
currentPage:(...) NO CSS KEY
```

I finally got the survey to appear as follows

```
 this.survey = new SurveyVue.SurveyModel(surveyJSON);
 this.survey.css = SurveyVue.surveyCss.getCss();
 console.log(this.survey);
```

I don't know why the model doesn't have the css property.
Any ideas?

Thanks!!

Note: In the surveyjs_vue_quickstart project I commented the following lines of code 

```
//var Survey = SurveyVue.Survey
//Survey.cssType = "bootstrap";
```

and I have checked that no css file is imported in the index. html.

The css property still appears in the model with which the survey is shown.

**Comment by dmitrykurmanov** [comment]
We've reproduced the bug with vue-cli@3.0.0-alpha.11
